public class BREApplicationInfo {
    public String applicationId {get;set;}
    public String applicationNumber {get;set;} 
    public String leadId {get;set;}
    public String transactionId {get;set;}
    public String branchCode {get;set;}
    public String branchName {get;set;}
    public String branchHub {get;set;}
    public String branchRegion {get;set;}
    public Datetime applicationDate {get;set;}
    public String applicationStage {get;set;}
    public String cityCategory {get;set;}
    public Integer applicationCounter {get;set;}
    public String roName {get;set;}
    public String roCode {get;set;}
    public String rmName {get;set;}
    public String rmCode {get;set;}
}