public class BREIncomeData {
    public Double documentIncome;	//100000
    public Double assessedIncome;	//100000
    public Double totalMonthlyIncome;	//200000
    public Double monthlyObligation;	//1000000
    // Optional - Differences Missed
    public Double verfiedAgriIncome = 0; // Optional
   public Double documentSalariedIncome=0;
    public Double documentITRIncome=0;
    public Double totalYearlyIncome=0;
    public Double yearlyObligation=0;
    
    
}