@isTest
public class DocCompressionRequestWrapperTest{
@isTest
    public static void TestMethod1(){
        Test.startTest();
        DocCompressionRequestWrapper ob = new DocCompressionRequestWrapper();
        ob.RequestId = '';
        ob.OriginatingChannel = 'OriginatingChannel1';
        ob.Filename = 'Filename1';
        ob.Base64string = 'QmFzZTY0c3RyaW5n';
        Test.stopTest();
        
    }
}