public with sharing Class FFRWrapper {
    public  Integer totalNoofVehicle {get;set;}
    public  Integer freeWithNoHypoOnRC {get;set;}
    public  Integer deemedFreeVehicle {get; set;}
    public  Integer totalFreeVehicle {get;set;}
    public  Integer financedVehicle {get; set;}
    public  double preFundingFFR {get; set;}
    public  Integer proposed {get; set;}
    public  double postFundingFFR{get;set;}
}