@isTest
public with sharing class leadDedupeJson {
    /*
     * public string id;
    public string ApplicationNumber;
    public string Product;
    public string LoanNumber;
    public string CustomerName;
    public string CustomerType;
    public string CustomerMobileNumber;
    public string ApplicationStatus;
    public string CreatedDate;
    public string RONameCode;
    public string ROMobileNumber;
    public string BranchNameCode;
    
    public leadDedupeJson() {

    }
*/
}