public class QuestionaireWrapperTemp {
    public String helpText;
    public String apiName;
    public String addressType;
    public Boolean borrower = false;
    public Boolean coBorrower = false;
    public Boolean guarantor = false;
    public Boolean office = false;
    public Boolean permanent = false;
    public Boolean current = false;
    public Boolean twoWheeler =false;
    public Boolean autoLoan = false;
    public String section;
    public Boolean isMandatory = false;
    public Boolean isMandatoryForVehicle = false;
    public Boolean vehicle = false;
}