@isTest
public class SIResponseWrapper {
/*
 * 	public class Messages {
		public Integer code;
		public String message;
	}

	public TransactionStatus TransactionStatus;

	public class TransactionStatus {
		public String ResponseCode;
		public String ResponseMessage;
		public ExtendedErrorDetails ExtendedErrorDetails;
	}

	public class ExtendedErrorDetails {
		public List<Messages> messages;
	}
*/
}